### ISSUE TITLE
When will you open source the code and data? 

### ISSUE THREAD

**Issue by CharlesGong12** [Quinn777/AtomThink#2]
Thanks for your excellent work.

When will you open source the code and data?

**Comment by Kun-Xiang** [comment]
Thank you for your attention! This week, we will be open-sourcing the inference code, along with the model weights and dataset.

**Comment by dydxdt** [comment]
> Thank you for your attention! This week, we will be open-sourcing the inference code, along with the model weights and dataset.

Also looking forward!
