### ISSUE TITLE
Question about the performance and training details of the "w. Formatted" baselines

### ISSUE THREAD

**Issue by xyliugo** [Quinn777/AtomThink#3]
Hi, thank you for your amazing work!

I noticed that the "w. Formatted" baseline seems to perform worse in the CoT setting compared to LLaVA-Llama3-8B and EMOVA-8B-200k after fine-tuning. It's somehow a bit strange to me. Could you confirm the specific training dataset size (I understand it to be the 26,108 meta samples, right?) and provide more details about the response format used in the "w. Formatted" training?

Thank you again for your great work, and I look forward to your explanation!

**Comment by Kun-Xiang** [comment]
Thank you for your attention! 

The experimental results here indeed demonstrate differences between MLLMs and LLMs. Our training set includes 26k meta-questions, with the instruction format as "<image><question>\nFirst perform reasoning, then finally answer the question and provide the final value at the end in the following format: Answer: xxx."

**Comment by xyliugo** [comment]
Thank you for your prompt reply! The data details are helpful. By the way, have you tried training on direct answer data, i.e., 26k meta-questions with only short answers (e.g., "The answer is xxx")? Will this lead to a performance drop or not? Thanks again!

**Comment by Kun-Xiang** [comment]
No, but our early experiments with some small subset (for example, about 5-10k of MAVIS metadata) for short responses did not show performance improvement.

**Comment by xyliugo** [comment]
Got it, thanks!
